//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Azs1212
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карты.
    /// </summary>
    // *** Start programmer edit section *** (Карты CustomAttributes)

    // *** End programmer edit section *** (Карты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартыE", new string[] {
            "НомерКарты as \'Номер карты\'",
            "НомерТелефона as \'Номер телефона\'",
            "Бонусы as \'Бонусы\'"})]
    public class Карты : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКарты;
        
        private int fНомерТелефона;
        
        private int fБонусы;
        
        private IIS.Azs1212.Оплата fОплата;
        
        // *** Start programmer edit section *** (Карты CustomMembers)

        // *** End programmer edit section *** (Карты CustomMembers)

        
        /// <summary>
        /// Бонусы.
        /// </summary>
        // *** Start programmer edit section *** (Карты.Бонусы CustomAttributes)

        // *** End programmer edit section *** (Карты.Бонусы CustomAttributes)
        public virtual int Бонусы
        {
            get
            {
                // *** Start programmer edit section *** (Карты.Бонусы Get start)

                // *** End programmer edit section *** (Карты.Бонусы Get start)
                int result = this.fБонусы;
                // *** Start programmer edit section *** (Карты.Бонусы Get end)

                // *** End programmer edit section *** (Карты.Бонусы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Карты.Бонусы Set start)

                // *** End programmer edit section *** (Карты.Бонусы Set start)
                this.fБонусы = value;
                // *** Start programmer edit section *** (Карты.Бонусы Set end)

                // *** End programmer edit section *** (Карты.Бонусы Set end)
            }
        }
        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (Карты.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (Карты.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (Карты.НомерКарты Get start)

                // *** End programmer edit section *** (Карты.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (Карты.НомерКарты Get end)

                // *** End programmer edit section *** (Карты.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Карты.НомерКарты Set start)

                // *** End programmer edit section *** (Карты.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (Карты.НомерКарты Set end)

                // *** End programmer edit section *** (Карты.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (Карты.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (Карты.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (Карты.НомерТелефона Get start)

                // *** End programmer edit section *** (Карты.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (Карты.НомерТелефона Get end)

                // *** End programmer edit section *** (Карты.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Карты.НомерТелефона Set start)

                // *** End programmer edit section *** (Карты.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (Карты.НомерТелефона Set end)

                // *** End programmer edit section *** (Карты.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Azs1212.Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Карты.Оплата CustomAttributes)

        // *** End programmer edit section *** (Карты.Оплата CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Оплата"})]
        public virtual IIS.Azs1212.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (Карты.Оплата Get start)

                // *** End programmer edit section *** (Карты.Оплата Get start)
                IIS.Azs1212.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (Карты.Оплата Get end)

                // *** End programmer edit section *** (Карты.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Карты.Оплата Set start)

                // *** End programmer edit section *** (Карты.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (Карты.Оплата Set end)

                // *** End programmer edit section *** (Карты.Оплата Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартыE", typeof(IIS.Azs1212.Карты));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Карты.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfКарты CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfКарты CustomAttributes)
    public class DetailArrayOfКарты : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Azs1212.DetailArrayOfКарты members)

        // *** End programmer edit section *** (IIS.Azs1212.DetailArrayOfКарты members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Карты by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Карты.
        /// </summary>
        public DetailArrayOfКарты(IIS.Azs1212.Оплата fОплата) : 
                base(typeof(Карты), ((ICSSoft.STORMNET.DataObject)(fОплата)))
        {
        }
        
        public IIS.Azs1212.Карты this[int index]
        {
            get
            {
                return ((IIS.Azs1212.Карты)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Azs1212.Карты dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
