//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Azs1212
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата.
    /// </summary>
    // *** Start programmer edit section *** (Оплата CustomAttributes)

    // *** End programmer edit section *** (Оплата CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатаE", new string[] {
            "Номер as \'Номер\'",
            "Количество as \'Количество\'",
            "ТипОплаты as \'Тип оплаты\'",
            "Сумма as \'Сумма\'"})]
    [View("ОплатаL", new string[] {
            "Номер as \'Номер\'",
            "Количество as \'Количество\'",
            "ТипОплаты as \'Тип оплаты\'",
            "Сумма as \'Сумма\'"})]
    public class Оплата : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private int fКоличество;
        
        private IIS.Azs1212.ТипОплаты fТипОплаты;
        
        private double fСумма;
        
        private IIS.Azs1212.Колонка fКолонка;
        
        private IIS.Azs1212.Терминал fТерминал;
        
        private IIS.Azs1212.DetailArrayOfКарты fКарты;
        
        // *** Start programmer edit section *** (Оплата CustomMembers)

        // *** End programmer edit section *** (Оплата CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Количество CustomAttributes)

        // *** End programmer edit section *** (Оплата.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Количество Get start)

                // *** End programmer edit section *** (Оплата.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Оплата.Количество Get end)

                // *** End programmer edit section *** (Оплата.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Количество Set start)

                // *** End programmer edit section *** (Оплата.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Оплата.Количество Set end)

                // *** End programmer edit section *** (Оплата.Количество Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Номер CustomAttributes)

        // *** End programmer edit section *** (Оплата.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Номер Get start)

                // *** End programmer edit section *** (Оплата.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Оплата.Номер Get end)

                // *** End programmer edit section *** (Оплата.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Номер Set start)

                // *** End programmer edit section *** (Оплата.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Оплата.Номер Set end)

                // *** End programmer edit section *** (Оплата.Номер Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Сумма CustomAttributes)

        // *** End programmer edit section *** (Оплата.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Сумма Get start)

                // *** End programmer edit section *** (Оплата.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (Оплата.Сумма Get end)

                // *** End programmer edit section *** (Оплата.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Сумма Set start)

                // *** End programmer edit section *** (Оплата.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (Оплата.Сумма Set end)

                // *** End programmer edit section *** (Оплата.Сумма Set end)
            }
        }
        
        /// <summary>
        /// ТипОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ТипОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.ТипОплаты CustomAttributes)
        public virtual IIS.Azs1212.ТипОплаты ТипОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ТипОплаты Get start)

                // *** End programmer edit section *** (Оплата.ТипОплаты Get start)
                IIS.Azs1212.ТипОплаты result = this.fТипОплаты;
                // *** Start programmer edit section *** (Оплата.ТипОплаты Get end)

                // *** End programmer edit section *** (Оплата.ТипОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ТипОплаты Set start)

                // *** End programmer edit section *** (Оплата.ТипОплаты Set start)
                this.fТипОплаты = value;
                // *** Start programmer edit section *** (Оплата.ТипОплаты Set end)

                // *** End programmer edit section *** (Оплата.ТипОплаты Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Колонка CustomAttributes)

        // *** End programmer edit section *** (Оплата.Колонка CustomAttributes)
        [PropertyStorage(new string[] {
                "Колонка"})]
        [NotNull()]
        public virtual IIS.Azs1212.Колонка Колонка
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Колонка Get start)

                // *** End programmer edit section *** (Оплата.Колонка Get start)
                IIS.Azs1212.Колонка result = this.fКолонка;
                // *** Start programmer edit section *** (Оплата.Колонка Get end)

                // *** End programmer edit section *** (Оплата.Колонка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Колонка Set start)

                // *** End programmer edit section *** (Оплата.Колонка Set start)
                this.fКолонка = value;
                // *** Start programmer edit section *** (Оплата.Колонка Set end)

                // *** End programmer edit section *** (Оплата.Колонка Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Терминал CustomAttributes)

        // *** End programmer edit section *** (Оплата.Терминал CustomAttributes)
        [PropertyStorage(new string[] {
                "Терминал"})]
        [NotNull()]
        public virtual IIS.Azs1212.Терминал Терминал
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Терминал Get start)

                // *** End programmer edit section *** (Оплата.Терминал Get start)
                IIS.Azs1212.Терминал result = this.fТерминал;
                // *** Start programmer edit section *** (Оплата.Терминал Get end)

                // *** End programmer edit section *** (Оплата.Терминал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Терминал Set start)

                // *** End programmer edit section *** (Оплата.Терминал Set start)
                this.fТерминал = value;
                // *** Start programmer edit section *** (Оплата.Терминал Set end)

                // *** End programmer edit section *** (Оплата.Терминал Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Карты CustomAttributes)

        // *** End programmer edit section *** (Оплата.Карты CustomAttributes)
        public virtual IIS.Azs1212.DetailArrayOfКарты Карты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Карты Get start)

                // *** End programmer edit section *** (Оплата.Карты Get start)
                if ((this.fКарты == null))
                {
                    this.fКарты = new IIS.Azs1212.DetailArrayOfКарты(this);
                }
                IIS.Azs1212.DetailArrayOfКарты result = this.fКарты;
                // *** Start programmer edit section *** (Оплата.Карты Get end)

                // *** End programmer edit section *** (Оплата.Карты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Карты Set start)

                // *** End programmer edit section *** (Оплата.Карты Set start)
                this.fКарты = value;
                // *** Start programmer edit section *** (Оплата.Карты Set end)

                // *** End programmer edit section *** (Оплата.Карты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаE", typeof(IIS.Azs1212.Оплата));
                }
            }
            
            /// <summary>
            /// "ОплатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаL", typeof(IIS.Azs1212.Оплата));
                }
            }
        }
    }
}
