//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Azs1212
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пистолет.
    /// </summary>
    // *** Start programmer edit section *** (Пистолет CustomAttributes)

    // *** End programmer edit section *** (Пистолет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПистолетE", new string[] {
            "Номер as \'Номер\'",
            "состояние as \'Состояние\'"})]
    [View("ПистолетL", new string[] {
            "Номер as \'Номер\'",
            "состояние as \'Состояние\'"})]
    public class Пистолет : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Azs1212.Состояние fсостояние;
        
        private IIS.Azs1212.СправочникЦен fСправочникЦен;
        
        // *** Start programmer edit section *** (Пистолет CustomMembers)

        // *** End programmer edit section *** (Пистолет CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Пистолет.Номер CustomAttributes)

        // *** End programmer edit section *** (Пистолет.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Пистолет.Номер Get start)

                // *** End programmer edit section *** (Пистолет.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Пистолет.Номер Get end)

                // *** End programmer edit section *** (Пистолет.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пистолет.Номер Set start)

                // *** End programmer edit section *** (Пистолет.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Пистолет.Номер Set end)

                // *** End programmer edit section *** (Пистолет.Номер Set end)
            }
        }
        
        /// <summary>
        /// состояние.
        /// </summary>
        // *** Start programmer edit section *** (Пистолет.состояние CustomAttributes)

        // *** End programmer edit section *** (Пистолет.состояние CustomAttributes)
        public virtual IIS.Azs1212.Состояние состояние
        {
            get
            {
                // *** Start programmer edit section *** (Пистолет.состояние Get start)

                // *** End programmer edit section *** (Пистолет.состояние Get start)
                IIS.Azs1212.Состояние result = this.fсостояние;
                // *** Start programmer edit section *** (Пистолет.состояние Get end)

                // *** End programmer edit section *** (Пистолет.состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пистолет.состояние Set start)

                // *** End programmer edit section *** (Пистолет.состояние Set start)
                this.fсостояние = value;
                // *** Start programmer edit section *** (Пистолет.состояние Set end)

                // *** End programmer edit section *** (Пистолет.состояние Set end)
            }
        }
        
        /// <summary>
        /// Пистолет.
        /// </summary>
        // *** Start programmer edit section *** (Пистолет.СправочникЦен CustomAttributes)

        // *** End programmer edit section *** (Пистолет.СправочникЦен CustomAttributes)
        [PropertyStorage(new string[] {
                "СправочникЦен"})]
        [NotNull()]
        public virtual IIS.Azs1212.СправочникЦен СправочникЦен
        {
            get
            {
                // *** Start programmer edit section *** (Пистолет.СправочникЦен Get start)

                // *** End programmer edit section *** (Пистолет.СправочникЦен Get start)
                IIS.Azs1212.СправочникЦен result = this.fСправочникЦен;
                // *** Start programmer edit section *** (Пистолет.СправочникЦен Get end)

                // *** End programmer edit section *** (Пистолет.СправочникЦен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Пистолет.СправочникЦен Set start)

                // *** End programmer edit section *** (Пистолет.СправочникЦен Set start)
                this.fСправочникЦен = value;
                // *** Start programmer edit section *** (Пистолет.СправочникЦен Set end)

                // *** End programmer edit section *** (Пистолет.СправочникЦен Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПистолетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПистолетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПистолетE", typeof(IIS.Azs1212.Пистолет));
                }
            }
            
            /// <summary>
            /// "ПистолетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПистолетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПистолетL", typeof(IIS.Azs1212.Пистолет));
                }
            }
        }
    }
}
