//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Azs1212
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Регист остатков.
    /// </summary>
    // *** Start programmer edit section *** (РегистОстатков CustomAttributes)

    // *** End programmer edit section *** (РегистОстатков CustomAttributes)
    [AutoAltered()]
    [Caption("Регист остатков")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РегистОстатковE", new string[0])]
    [View("РегистОстатковL", new string[0])]
    public class РегистОстатков : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Azs1212.Оплата fОплата;
        
        private IIS.Azs1212.Резервуар fРезервуар;
        
        // *** Start programmer edit section *** (РегистОстатков CustomMembers)

        // *** End programmer edit section *** (РегистОстатков CustomMembers)

        
        /// <summary>
        /// Регист остатков.
        /// </summary>
        // *** Start programmer edit section *** (РегистОстатков.Оплата CustomAttributes)

        // *** End programmer edit section *** (РегистОстатков.Оплата CustomAttributes)
        [PropertyStorage(new string[] {
                "Оплата"})]
        [NotNull()]
        public virtual IIS.Azs1212.Оплата Оплата
        {
            get
            {
                // *** Start programmer edit section *** (РегистОстатков.Оплата Get start)

                // *** End programmer edit section *** (РегистОстатков.Оплата Get start)
                IIS.Azs1212.Оплата result = this.fОплата;
                // *** Start programmer edit section *** (РегистОстатков.Оплата Get end)

                // *** End programmer edit section *** (РегистОстатков.Оплата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистОстатков.Оплата Set start)

                // *** End programmer edit section *** (РегистОстатков.Оплата Set start)
                this.fОплата = value;
                // *** Start programmer edit section *** (РегистОстатков.Оплата Set end)

                // *** End programmer edit section *** (РегистОстатков.Оплата Set end)
            }
        }
        
        /// <summary>
        /// Регист остатков.
        /// </summary>
        // *** Start programmer edit section *** (РегистОстатков.Резервуар CustomAttributes)

        // *** End programmer edit section *** (РегистОстатков.Резервуар CustomAttributes)
        [PropertyStorage(new string[] {
                "Резервуар"})]
        [NotNull()]
        public virtual IIS.Azs1212.Резервуар Резервуар
        {
            get
            {
                // *** Start programmer edit section *** (РегистОстатков.Резервуар Get start)

                // *** End programmer edit section *** (РегистОстатков.Резервуар Get start)
                IIS.Azs1212.Резервуар result = this.fРезервуар;
                // *** Start programmer edit section *** (РегистОстатков.Резервуар Get end)

                // *** End programmer edit section *** (РегистОстатков.Резервуар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РегистОстатков.Резервуар Set start)

                // *** End programmer edit section *** (РегистОстатков.Резервуар Set start)
                this.fРезервуар = value;
                // *** Start programmer edit section *** (РегистОстатков.Резервуар Set end)

                // *** End programmer edit section *** (РегистОстатков.Резервуар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РегистОстатковE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистОстатковE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистОстатковE", typeof(IIS.Azs1212.РегистОстатков));
                }
            }
            
            /// <summary>
            /// "РегистОстатковL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РегистОстатковL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РегистОстатковL", typeof(IIS.Azs1212.РегистОстатков));
                }
            }
        }
    }
}
